version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Project/WinHubX/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
