<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BlackSharp.Core" Version="1.2.2" />
    <PackageVersion Include="DiscUtils.Udf" Version="0.16.13" />
    <PackageVersion Include="HartUI.Winforms" Version="2026.8.24" />
    <PackageVersion Include="LibreHardwareMonitorLib" Version="0.9.7-pre749" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Testing.Extensions.Telemetry" Version="2.5.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport.Abstractions" Version="2.5.1" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.5.1" />
    <PackageVersion Include="Microsoft.Testing.Platform.MSBuild" Version="2.5.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="System.ServiceProcess.ServiceController" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="TaskScheduler" Version="2.12.2" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>
</Project>
